### ISSUE TITLE
Can't make with tdlib 1.6.8

### ISSUE THREAD

**Issue by 1roxv** [m-mehdiansari/tdbot#1]
Hi! How fix or how i can build with 1.6.3? 

```
[ 65%] Building CXX object CMakeFiles/telegram-bot.dir/cliclient.cpp.o
/home/ubuntu/tdbot/cliclient.cpp: In member function ‘virtual void CliSockFd::sock_read(td::uint64)’:
/home/ubuntu/tdbot/cliclient.cpp:82:14: error: ‘can_read’ is not a member of ‘td’
   82 |   while (td::can_read (fd_)) {
      |              ^~~~~~~~
/home/ubuntu/tdbot/cliclient.cpp: In member function ‘virtual void CliStdFd::sock_read(td::uint64)’:
/home/ubuntu/tdbot/cliclient.cpp:108:31: error: ‘can_read’ is not a member of ‘td’
  108 |   while (!half_closed_ && td::can_read (td::Stdin())) {
      |                               ^~~~~~~~
/home/ubuntu/tdbot/cliclient.cpp: In member function ‘virtual void CliSockFd::sock_write(td::uint64)’:
/home/ubuntu/tdbot/cliclient.cpp:134:14: error: ‘can_write’ is not a member of ‘td’
  134 |   while (td::can_write (fd_) && out_.length () > 0) {
      |              ^~~~~~~~~
/home/ubuntu/tdbot/cliclient.cpp: In member function ‘virtual void CliStdFd::sock_write(td::uint64)’:
/home/ubuntu/tdbot/cliclient.cpp:145:14: error: ‘can_write’ is not a member of ‘td’
  145 |   while (td::can_write (td::Stdout()) && out_.length () > 0) {
      |              ^~~~~~~~~
/home/ubuntu/tdbot/cliclient.cpp: In member function ‘virtual void CliSockFd::sock_close(td::uint64)’:
/home/ubuntu/tdbot/cliclient.cpp:156:11: error: ‘can_close’ is not a member of ‘td’
  156 |   if (td::can_close (fd_)) {
      |           ^~~~~~~~~
/home/ubuntu/tdbot/cliclient.cpp: In member function ‘virtual void CliStdFd::sock_close(td::uint64)’:
/home/ubuntu/tdbot/cliclient.cpp:171:11: error: ‘can_close’ is not a member of ‘td’
  171 |   if (td::can_close (td::Stdin())) {
      |           ^~~~~~~~~
/home/ubuntu/tdbot/cliclient.cpp:174:11: error: ‘can_close’ is not a member of ‘td’
  174 |   if (td::can_close (td::Stdout())) {
      |           ^~~~~~~~~
/home/ubuntu/tdbot/cliclient.cpp: In member function ‘virtual void CliClient::loop()’:
/home/ubuntu/tdbot/cliclient.cpp:325:16: error: ‘can_read’ is not a member of ‘td’
  325 |     while (td::can_read (listen_)) {
      |                ^~~~~~~~
/home/ubuntu/tdbot/cliclient.cpp:333:13: error: ‘can_close’ is not a member of ‘td’
  333 |     if (td::can_close (listen_)) {
      |             ^~~~~~~~~
make[2]: *** [CMakeFiles/telegram-bot.dir/build.make:76: CMakeFiles/telegram-bot.dir/cliclient.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:382: CMakeFiles/telegram-bot.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by m-mehdiansari** [comment]
Hi
TdLib is now updated and there is no update for TdBot, so it is not possible to build.

**Comment by 1roxv** [comment]
You can upload release?
